### ISSUE TITLE
Debounce or throttle on-scroll callback

### ISSUE THREAD

**Issue by hlfcoding** [lorenzofox3/lrStickyHeader#1]
This [line](https://github.com/lorenzofox3/lrStickyHeader/blob/158575d/lrStickyHeader.js#L110) is directly binding the callback to the scroll event. Repeatedly calling functions during scroll can hurt performance.

**Comment by lorenzofox3** [comment]
I don't think the [code running on each event](https://github.com/lorenzofox3/lrStickyHeader/blob/master/lrStickyHeader.js#L47-L49) is expensive (although it accesses dom properties)

Have you tried anything ? 

[here it with debounce](http://plnkr.co/edit/SYQeh9wxxOzqfAxAsF5C?p=preview), I don't see much difference
