### ISSUE TITLE
update to be responsive

### ISSUE THREAD

**Issue by bbodenmiller** [lorenzofox3/lrStickyHeader#18]
Based on the demo it appears that if you resize the window the table headers appear misaligned.

![image](https://cloud.githubusercontent.com/assets/1192780/20945664/059ef4e2-bbbd-11e6-8ead-6e315760f07b.png)

**Comment by lorenzofox3** [comment]
yes that is the known "bug". you have to use manually the setWidht() method of the api. As there are different strategies to handle window resize, I let the user choose what is more appropriate for its usecase
